import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const scriptPath = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(scriptPath), "..");
const checkOnly = process.argv.includes("--check");

const versionPath = path.join(root, "VERSION");
const version = fs.readFileSync(versionPath, "utf8").trim();

const semverPattern =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

if (!semverPattern.test(version)) {
  throw new Error(`VERSION contains an invalid semantic version: ${version}`);
}

const changes = [];

function queueText(relativePath, nextContent) {
  const absolutePath = path.join(root, relativePath);
  const currentContent = fs.existsSync(absolutePath)
    ? fs.readFileSync(absolutePath, "utf8")
    : "";

  if (currentContent !== nextContent) {
    changes.push({ relativePath, absolutePath, nextContent });
  }
}

function queueJson(relativePath, transform) {
  const absolutePath = path.join(root, relativePath);
  const value = JSON.parse(fs.readFileSync(absolutePath, "utf8"));
  transform(value);
  queueText(relativePath, `${JSON.stringify(value, null, 2)}\n`);
}

queueJson("package.json", (value) => {
  value.version = version;
});

queueJson("apps/shell/package.json", (value) => {
  value.version = version;
});

queueJson("apps/shell/src-tauri/tauri.conf.json", (value) => {
  value.version = version;
});

queueJson("release/manifest.json", (value) => {
  value.version = version;
});

const cargoPath = path.join(root, "Cargo.toml");
const cargo = fs.readFileSync(cargoPath, "utf8");
const workspaceVersionPattern =
  /(\[workspace\.package\][\s\S]*?\nversion\s*=\s*")[^"]+(")/;

if (!workspaceVersionPattern.test(cargo)) {
  throw new Error("Could not locate [workspace.package] version in Cargo.toml");
}

queueText(
  "Cargo.toml",
  cargo.replace(workspaceVersionPattern, `$1${version}$2`),
);

queueText(
  "apps/shell/src/app/version.ts",
  [
    "// Generated by scripts/sync-version.mjs from the repository VERSION file.",
    "// Do not edit this file directly.",
    `export const JONEX_VERSION = "${version}";`,
    "",
  ].join("\n"),
);

const lockPath = path.join(root, "package-lock.json");

if (fs.existsSync(lockPath)) {
  const lock = JSON.parse(fs.readFileSync(lockPath, "utf8"));
  lock.version = version;

  if (lock.packages?.[""]) {
    lock.packages[""].version = version;
  }

  if (lock.packages?.["apps/shell"]) {
    lock.packages["apps/shell"].version = version;
  }

  queueText("package-lock.json", `${JSON.stringify(lock, null, 2)}\n`);
}

if (checkOnly) {
  if (changes.length > 0) {
    console.error("JØNEX version metadata is out of sync:");

    for (const change of changes) {
      console.error(`  ${change.relativePath}`);
    }

    process.exit(1);
  }

  console.log(`JØNEX version metadata is synchronized at ${version}.`);
  process.exit(0);
}

for (const change of changes) {
  fs.mkdirSync(path.dirname(change.absolutePath), { recursive: true });
  fs.writeFileSync(change.absolutePath, change.nextContent, "utf8");
  console.log(`updated ${change.relativePath}`);
}

console.log(`JØNEX version synchronized to ${version}.`);